### ISSUE TITLE
Arch Linux packaging

### ISSUE THREAD

**Issue by z3ntu** [cyanogen/uchroma#11]
Does this list of files that get installed with the package seem correct to you? http://pastebin.com/u4q4t9Up

**Comment by z3ntu** [comment]
Also https://github.com/cyanogen/uchroma/blob/master/Makefile#L2 should be `PYTHONDIR?=$(shell python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")` as the current solution can break on some specific distributions (such as on some openSUSE versions)

**Comment by cyanogen** [comment]
List looks OK. Be sure to enable the user service.

**Comment by z3ntu** [comment]
Should be finished: https://aur.archlinux.org/packages/uchroma/ . I don't enable the service automatically but print a message on how to do it because it's the preferred way on Arch afaik.

**Comment by jramapuram** [comment]
@z3ntu : Looks like this installs python2-* deps also? I dont see it as a requirement in your build though, but here are some logs:

```bash
Checking integrity...
Loading packages files...
Checking file conflicts...
Checking available disk space...
Installing python-wrapt (1.10.8-2)...
Installing python-decorator (4.0.11-1)...
Installing python-traitlets (4.3.2-1)...
Installing python-ruamel-yaml (0.13.14-1)...
Installing python-scipy (0.18.1-2)...
Installing python-pytz (2016.10-2)...
Installing python-dateutil (2.6.0-2)...
Installing python-cycler (0.10.0-2)...
Installing python-matplotlib (2.0.0-1)...
Installing python-networkx (1.11-2)...
Installing python-olefile (0.43-2)...
Installing python-pillow (4.0.0-2)...
Installing python2-pyparsing (2.1.10-2)...
Installing python2-six (1.10.0-3)...
Installing python2-packaging (16.8-2)...
Installing python2-appdirs (1.4.2-1)...
Installing python2-setuptools (1:34.3.1-1)...
Installing cython2 (0.25.2-2)...
Installing cython (0.25.2-2)...
Installing python2-numpy (1.12.0-1)...
Installing python2-scipy (0.18.1-2)...
Installing python2-pytz (2016.10-2)...
Installing python2-sip (4.19.1-1)...
Installing python2-pyqt5 (5.8-1)...
Installing python2-dateutil (2.6.0-2)...
Installing python2-cycler (0.10.0-2)...
Installing python2-backports (1.0-1)...
Installing python2-backports.functools_lru_cache (1.3-1)...
Installing python2-matplotlib (2.0.0-1)...
Installing python2-decorator (4.0.11-1)...
Installing python2-networkx (1.11-2)...
Installing python2-olefile (0.43-2)...
Installing python2-pillow (4.0.0-2)...
Installing python-frozendict (1.2-2)...
Installing python-ptyprocess (0.5.1-2)...
Installing python-pexpect (4.2.1-2)...
Installing python2-ptyprocess (0.5.1-2)...
Installing python2-pexpect (4.2.1-2)...
Installing python-ply (3.10-1)...
Installing python-pycparser (2.17-2)...
Installing python-cffi (1.9.1-2)...
Installing hidapi (0.8.0rc1-2)...
Installing python-hidapi (0.7.99.20-1)...
Installing python-py (1.4.32-2)...
Installing python-pytest (3.0.6-1)...
Installing python-pandas (0.19.2-2)...
Installing python-psutil (5.1.3-1)...
Installing python-pyzmq (16.0.2-2)...
Installing python-nose (1.3.7-3)...
Installing python-pytest-runner (2.11.1-1)...
...
```

**Comment by jramapuram** [comment]
Also it fails, full logs here :  https://gist.github.com/jramapuram/9b01e9d96b19a4c0f96efcdf69f781fd

**Comment by z3ntu** [comment]
1. What AUR helper are you using?
2. I know that `python-locket` fails to build but 1. that's not my package and 2. I [flagged it out-of-date today because I noticed the problem](https://aur.archlinux.org/pkgbase/python-locket/flag-comment/). Building it with `--nocheck` (makepkg flag) should let you skip the check.

**Comment by jramapuram** [comment]
Running Manjaro, so it should be pamac which is backed by yaourt

**Comment by z3ntu** [comment]
yaourt probably installs all packages from a split package. Nothing I or anyone except the yaourt people can change. I use pacaur and it works fine there. (also the behaviour isn't related to the PKGBUILD at all)

**Comment by z3ntu** [comment]
@cyanogen Can you add a note how to install on Arch Linux to the readme? Then this issue can be closed 👍

**Comment by jramapuram** [comment]
@z3ntu : on a slightly different note, are you running python 3.6 ? I can't seem to get uchroma to startup due to some singleton issue as described https://github.com/cyanogen/uchroma/issues/13

**Comment by cyanogen** [comment]
Try the 1.0.1 release.

**Comment by cyanogen** [comment]
@z3ntu I'm not an Arch guy at all, what should the instructions look like?

**Comment by z3ntu** [comment]
Most people use ["AUR Helpers"](https://wiki.archlinux.org/index.php/AUR_helpers) which is an application that automates the installation from "AUR" (custom packages from the community where no binary form is available) packages but unfortunately there is a wide range of different applications to do basically the same job.
But I think linking to https://aur.archlinux.org/packages/uchroma/ is enough for Arch users to understand what they have to do.
