### ISSUE TITLE
Kraken 7.1 Chroma

### ISSUE THREAD

**Issue by z3ntu** [cyanogen/uchroma#14]
It's the only device right now I own that gets listed (I own BlackWidow Chroma, DeathAdder Chroma & Kraken 7.1 Chroma). When I try to set the brightness with `uchroma brightness 100`, nothing changes and I have the following output in my systemd journal: http://pastebin.com/cZ5Ax2zC

**Comment by cyanogen** [comment]
Interesting, something funky with the serial.. I have been testing with a 7.1 and it's been OK. Maybe there is some variance, I can add a workaround.

**Comment by cyanogen** [comment]
Also, send me the the output of lsusb -vvv, those other devices should be supported unless udev didn't tag them. What OS?

**Comment by cyanogen** [comment]
Meant firmware version, not serial.

**Comment by z3ntu** [comment]
`lsusb -vvv`: http://pastebin.com/HEdSCLeZ
OS: Arch Linux with the package I created (`/etc/udev/rules.d/70-uchroma.rules` exists (sidenote: it should be in `/usr/lib/udev/rules.d/` and also the hwdb file).

**Comment by cyanogen** [comment]
What does ls -l /dev/bus/usb/003/* look like? I'm assuming that Arch supports the uaccess tag, AFAIK this is pretty standard now but I want to be sure.

**Comment by cyanogen** [comment]
Also, let me see what this looks like:

python3 -c "import hidapi; print([a.path for a in list(hidapi.enumerate())])" 

^^^ Should give a list of usb identifiers, not hidraw paths. 

I haven't tested much with the hidraw backend, but I suppose we should support both hidraw and libusb. If this is the case, bulid with libusb support until it's fixed.

**Comment by z3ntu** [comment]
```
luca@g550jk ~> python3 -c "import hidapi; print([a.path for a in list(hidapi.enumerate())])"
[b'0003:0028:00', b'0003:0028:01', b'0003:0028:02', b'0003:0026:03', b'0003:002a:00', b'0003:002a:01', b'0003:002a:02', b'0003:0029:00', b'0003:0029:01', b'0003:0029:02', b'0003:0029:03', b'0003:0029:04']
luca@g550jk ~> ls -l /dev/bus/usb/003/*
crw-rw-r--  1 root   root     189, 256  8. Mär 22:06 /dev/bus/usb/003/001
crw-rw-r--  1 root   root     189, 259  8. Mär 22:06 /dev/bus/usb/003/004
crw-rw----+ 1 root   adbusers 189, 271  8. Mär 22:06 /dev/bus/usb/003/016
crw-rw-r--  1 root   root     189, 284  9. Mär 10:47 /dev/bus/usb/003/029
crw-rw-r--  1 root   root     189, 291  9. Mär 16:33 /dev/bus/usb/003/036
crw-rw-r--  1 root   root     189, 292  9. Mär 16:33 /dev/bus/usb/003/037
crw-rw-r--+ 1 root   root     189, 293  9. Mär 16:38 /dev/bus/usb/003/038
crw-rw-r--+ 1 usbmux root     189, 294  9. Mär 16:33 /dev/bus/usb/003/039
crw-rw-r--+ 1 root   root     189, 295  9. Mär 16:38 /dev/bus/usb/003/040
crw-rw-rw-+ 1 root   root     189, 296  9. Mär 16:38 /dev/bus/usb/003/041
crw-rw-r--+ 1 root   root     189, 297  9. Mär 16:38 /dev/bus/usb/003/042
```

**Comment by cyanogen** [comment]
Permissions look OK. 

Let me test this thing on Python 3.6 before doing anything else, this isn't the first report of breakage on 3.6 I've seen.

**Comment by cyanogen** [comment]
Yes, 3.6 was broken due to some cruft.
