### ISSUE TITLE
E: Unable to locate package uchroma

### ISSUE THREAD

**Issue by BIGBALLON** [cyanogen/uchroma#15]
I just use the following cmd:

sudo add-apt-repository ppa:cyanogen/uchroma
sudo apt update
sudo apt install uchroma

Then I get

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package uchroma

I don't know why.
anyone has the some question?

**Comment by cyanogen** [comment]
Which Ubuntu release are you on?

**Comment by BIGBALLON** [comment]
I just use Ubuntu 16.04 LTS. 
and I upadted kernel to version 4.8

**Comment by cyanogen** [comment]
Hrm, I swear I published it to the PPA :)  Will get it up there in a few.

**Comment by cyanogen** [comment]
Should be installable now, let me know how it works for you as I haven't tested much on Xenial.

**Comment by BIGBALLON** [comment]
bigballon@Blade:~$ sudo apt-get update
Hit:1 http://tw.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://tw.archive.ubuntu.com/ubuntu xenial-updates InRelease                     
Hit:3 http://tw.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                                   
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                                      
Hit:5 http://ppa.launchpad.net/cyanogen/uchroma/ubuntu xenial InRelease
Get:6 http://ppa.launchpad.net/cyanogen/uchroma/ubuntu xenial/main Sources [4832 B]
Fetched 4832 B in 1s (3450 B/s)    
Reading package lists... Done
bigballon@Blade:~$ sudo apt install uchroma
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package uchroma


sad ... It still doesn't work in Xenial.

**Comment by cyanogen** [comment]
Yeah, the build failed due to a couple of old packages. Almost got it.

**Comment by cyanogen** [comment]
Packages are built and uploaded now

**Comment by BIGBALLON** [comment]
now, I install uchroma successfully.
but .... I get the following new problem:

Traceback (most recent call last):
  File "/usr/bin/uchroma", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'hidapi' distribution was not found and is required by uchroma

**Comment by cyanogen** [comment]
I pulled the packages down, will do end-to-end testing tonight before uploading a new rev.

**Comment by cyanogen** [comment]
Any issue with the 1.0.1 packages?

**Comment by BIGBALLON** [comment]
It's ok for ubuntu16.04.. thanks for your hard work!
But i think there are still lots of problem if install linux On Razer

**Comment by cyanogen** [comment]
Besides issues like thermal, display backlight, etc etc, if there's something that is in scope for this project, would like to hear it :)
