### ISSUE TITLE
Brightness not restored after resume from suspend

### ISSUE THREAD

**Issue by tschreibe** [cyanogen/uchroma#30]
I have a RBS Late 2016 and sometimes the brightness is not restored after a resume from suspend.
It looks like it needs 2 suspend/resume to trigger the issue.
I noticed that the bug occurs when the light is turned off abruptly at suspend but does not occur when the light gradually fades out at suspend.

I figured out that I can workaround it if I comment this piece of code in uchroma/server/device_base.py. With the comment, the light always fades out gradually.

l. 235:
`if fast:
    self._set_brightness(0)
  else:
    if self._device_open():
      self._brightness_animator.animate(self.brightness, 0,
                                                  done_cb=self._done_cb)`

Sorry, I'd like to eventually make a pull request but I'm currently not confident enough in python to try something. I hope my description helps anyway.

Other than that, it's a pretty neat package.

**Comment by cyanogen** [comment]
This is fixed in the 1.0.3 release.
