### ISSUE TITLE
openrazer compatibility ?

### ISSUE THREAD

**Issue by dimyme** [cyanogen/uchroma#34]
Is there a chance to make this so that it coexists with openrazer and allows for persistent makros ?

**Comment by ifohancroft** [comment]
I am sorry for commenting on a closed ticket.

1. I am not sure what @dimyme meant by uchroma coexisting with openrazer and why they have closed the ticket.
2. It seems there are many projects about controlling/configuring Razer devices under Linux. What's your stance on the idea of merging them? Maybe into Open Razer?
